### PR TITLE
Adding unit tests for my .mget() fixes.

### PR DESCRIPTION
**Pull request by jpodwys**
@darrylwest

### CODE REVIEW

**Comment by darrylwest** [comment]
Ok I merged your tests as well.  Thanks for your help...

**Comment by darrylwest** [comment]
to formally add you as a contributor, I need an email and a link to your site.  and if you are interested, we could exchange skype handles.  we use it for our daily scrums, screen shares and ad-hoc chats.

let me know...

**Comment by jpodwys** [comment]
My website is joepodwys.com. I'm happy to give you my email address, I just need to know whether it's going to be posted somewhere public so I know which address to give you. As for skype, I'm on skype perhaps twice a year, so it wouldn't be an effective means of communication for me.

**Comment by darrylwest** [comment]
when I add you as a collaborator, you get an entry into the package.json file and to the github project collaborators.  so the url and email appear on github and npm.

**Comment by jpodwys** [comment]
I was unaware of that. Thanks. My email is joseph@podwys.com.

**Comment by darrylwest** [comment]
ok, I added you to both github and the package file.  it sometimes takes a while to show up on github, but you should be able to clone the original project and do commits.  

I have a javascript standards document here: http://blog.raincitysoftware.com/docs/JavascriptCodingStandards.html ; It's probably good to review.  

Let me know if there are other projects that you would be interested in--I always need help.  

Thanks...

**Comment by jpodwys** [comment]
Thanks for the link! Always good to keep consistency with the existing code base's styles.

**Pull request merged**
