### PR TITLE
Fixing .mget() implementation.

### PR DESCRIPTION
**Pull request by jpodwys**
Fixing the following `.mget()` issues:
- Values returned should be in the same order as the requested keys
- Keys not found should return `null`

@darrylwest @raincity

### CODE REVIEW

**Comment by jpodwys** [comment]
Fixed unit test. Funny thing is, it wasn't my code change causing the failure. Looks like it was expecting 123 member functions and there are actually 127.
@raincity @darrylwest

**Comment by darrylwest** [comment]
yes, it's the number of methods inside redis proper that caused the unit test to fail.   but I patched your fix into the develop branch manually.

I need to fix the too-brittle unit test that was broken, then write a unit test for your change. (unless you want to do that).

Can I have you work on the develop branch for fixes?

**Comment by jpodwys** [comment]
I'm happy to add the unit tests to your develop branch. Is it tacky of me to also want contributor credit for the `.mget()` fix? I'm not accustomed to having to commit to a specific branch. In my experience, people pull the PR, test it locally, and then merge it into master.

**Comment by darrylwest** [comment]
Thanks for your help on this.  I was able to get more robusts tests in place and republish to npm, version 00.90.19.

If you are interested, I would like to add you as a contributor.  Then, you could work on the develop branch directly without doing the pull request thing.

What do you think?

**Comment by jpodwys** [comment]
That sounds great. Thanks for your quick response today.

**Pull request closed without merging**
